apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      volumeMounts:
        - name: host-data
          mountPath: /host
  volumes:
    - name: host-data
      hostPath:
        path: /
        type: Directory

