apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireSafePod
metadata:
  name: require-safe-pod-audit-zone
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["audit-zone"]

